version: "3.8"
services:
  api-partner:
    build:
      context: ./apps/api
      dockerfile: partner.Dockerfile
    image: ${PROJECT_NAME}-api-partner
    container_name: ${PROJECT_NAME}-api-partner
    env_file:
      - ./apps/api/.env
    volumes:
      - ./apps/api:/app
    ports:
      - 9001:9001
    healthcheck:
      test: curl http://api-partner:9000/healthcheck || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s

  api-op:
    build:
      context: ./apps/api
      dockerfile: op.Dockerfile
    image: ${PROJECT_NAME}-api-op
    container_name: ${PROJECT_NAME}-api-op
    env_file:
      - ./apps/api/.env
    volumes:
      - ./apps/api:/app
    ports:
      - 9000:9000
    healthcheck:
      test: curl http://api-op:9000/healthcheck || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s

  web-op:
    build:
      context: ./apps/web/op
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-web-op
    restart: on-failure
    container_name: ${PROJECT_NAME}-web-op
    ports:
      - "82:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 30s
      retries: 10
    depends_on:
      api-op:
        condition: service_healthy

  web-partner:
    build:
      context: ./apps/web/partner
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-web-partner
    restart: on-failure
    container_name: ${PROJECT_NAME}-web-partner
    ports:
      - "81:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 30s
      retries: 10
    depends_on:
      api-partner:
        condition: service_healthy
