from .auth import router as auth_router
from .card import router as card_router
from .card import router_history as card_history_router
from .control import router as control_router
from .partner import router as partner_router
from .path import router as path_router
from .pos import router as pos_router
from .promotion import router as promotion_router
from .promotion import router_condition as promotion_condition_router
from .target import router as target_router
from .token import router as token_router
from .user import router as user_router
from .work import router as work_router
