version: "3.7"
services:
  server:
    image: refuel
    container_name: citycard-server
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    restart: always
    networks:
      - new
    environment:
      - POSTGRES_DSN=${DATABASE_URL}
    ports:
    - "8080:${PORT}"

networks:
  new: